<a href="https://colab.research.google.com/github/Anjani11/Product_length_prediction/blob/main/PRODUCT_LENGTH_PREDICTION.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_percentage_error
from sklearn.preprocessing import OneHotEncoder
import tensorflow as tf
from tensorflow import keras
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.feature_selection import chi2
import re
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import classification_report, f1_score, accuracy_score, confusion_matrix

In [ ]:
trainData=pd.read_csv("/content/drive/MyDrive/DATA/datasetb2d9982/dataset/train.csv",index_col=False)

In [ ]:
#trainData = TrainData.reset_index(drop=True)
#trainData.reset_index(drop=True, inplace=True)
#trainData prints first 5 rows
trainData.head()

,PRODUCT_ID,TITLE,BULLET_POINTS,DESCRIPTION,PRODUCT_TYPE_ID,PRODUCT_LENGTH
0,1925202,ArtzFolio Tulip Flowers Blackout Curtain for D...,[LUXURIOUS & APPEALING: Beautiful custom-made ...,NaN,1650,2125.980000
1,2673191,Marks & Spencer Girls' Pyjama Sets T86_2561C_N...,"[Harry Potter Hedwig Pyjamas (6-16 Yrs),100% c...",NaN,2755,393.700000
2,2765088,PRIKNIK Horn Red Electric Air Horn Compressor ...,"[Loud Dual Tone Trumpet Horn, Compatible With ...","Specifications: Color: Red, Material: Aluminiu...",7537,748.031495
3,1594019,ALISHAH Women's Cotton Ankle Length Leggings C...,[Made By 95%cotton and 5% Lycra which gives yo...,AISHAH Women's Lycra Cotton Ankel Leggings. Br...,2996,787.401574
4,283658,The United Empire Loyalists: A Chronicle of th...,NaN,NaN,6112,598.424000

In [ ]:
trainData.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2249698 entries, 0 to 2249697
Data columns (total 6 columns):
 #   Column           Dtype
---  ------           -----
 0   PRODUCT_ID       int64
 1   TITLE            object
 2   BULLET_POINTS    object
 3   DESCRIPTION      object
 4   PRODUCT_TYPE_ID  int64
 5   PRODUCT_LENGTH   float64
dtypes: float64(1), int64(2), object(3)
memory usage: 103.0+ MB

In [ ]:
trainData.describe()

         PRODUCT_ID  PRODUCT_TYPE_ID  PRODUCT_LENGTH
count  2.249698e+06     2.249698e+06    2.249698e+06
mean   1.499795e+06     4.000456e+03    4.071839e+03
std    8.661944e+05     3.966146e+03    1.351685e+06
min    1.000000e+00     0.000000e+00    1.000000e+00
25%    7.494795e+05     2.300000e+02    5.118110e+02
50%    1.499558e+06     2.916000e+03    6.630000e+02
75%    2.250664e+06     6.403000e+03    1.062992e+03
max    2.999999e+06     1.342000e+04    1.885801e+09

In [ ]:
trainData.shape

(2249698, 6)

In [ ]:
trainData.isnull().sum()

PRODUCT_ID               0
TITLE                   12
BULLET_POINTS       837364
DESCRIPTION        1157381
PRODUCT_TYPE_ID          0
PRODUCT_LENGTH           0
dtype: int64

In [ ]:
trainData.interpolate(inplace=True)

In [ ]:
trainData.head()

,PRODUCT_ID,TITLE,BULLET_POINTS,DESCRIPTION,PRODUCT_TYPE_ID,PRODUCT_LENGTH
0,1925202,ArtzFolio Tulip Flowers Blackout Curtain for D...,[LUXURIOUS & APPEALING: Beautiful custom-made ...,NaN,1650,2125.980000
1,2673191,Marks & Spencer Girls' Pyjama Sets T86_2561C_N...,"[Harry Potter Hedwig Pyjamas (6-16 Yrs),100% c...",NaN,2755,393.700000
2,2765088,PRIKNIK Horn Red Electric Air Horn Compressor ...,"[Loud Dual Tone Trumpet Horn, Compatible With ...","Specifications: Color: Red, Material: Aluminiu...",7537,748.031495
3,1594019,ALISHAH Women's Cotton Ankle Length Leggings C...,[Made By 95%cotton and 5% Lycra which gives yo...,AISHAH Women's Lycra Cotton Ankel Leggings. Br...,2996,787.401574
4,283658,The United Empire Loyalists: A Chronicle of th...,NaN,NaN,6112,598.424000

In [ ]:
trainData.isnull().sum()

PRODUCT_ID               0
TITLE                   12
BULLET_POINTS       837364
DESCRIPTION        1157381
PRODUCT_TYPE_ID          0
PRODUCT_LENGTH           0
dtype: int64

In [ ]:
trainData['TITLE'].fillna('',inplace=True)

In [ ]:
trainData['BULLET_POINTS'].fillna('missing',inplace=True)
trainData['DESCRIPTION'].fillna('missing',inplace=True)

In [ ]:
trainData.isnull().sum()

PRODUCT_ID         0
TITLE              0
BULLET_POINTS      0
DESCRIPTION        0
PRODUCT_TYPE_ID    0
PRODUCT_LENGTH     0
dtype: int64

In [ ]:
trainData.head()

,PRODUCT_ID,TITLE,BULLET_POINTS,DESCRIPTION,PRODUCT_TYPE_ID,PRODUCT_LENGTH
0,1925202,ArtzFolio Tulip Flowers Blackout Curtain for D...,[LUXURIOUS & APPEALING: Beautiful custom-made ...,missing,1650,2125.980000
1,2673191,Marks & Spencer Girls' Pyjama Sets T86_2561C_N...,"[Harry Potter Hedwig Pyjamas (6-16 Yrs),100% c...",missing,2755,393.700000
2,2765088,PRIKNIK Horn Red Electric Air Horn Compressor ...,"[Loud Dual Tone Trumpet Horn, Compatible With ...","Specifications: Color: Red, Material: Aluminiu...",7537,748.031495
3,1594019,ALISHAH Women's Cotton Ankle Length Leggings C...,[Made By 95%cotton and 5% Lycra which gives yo...,AISHAH Women's Lycra Cotton Ankel Leggings. Br...,2996,787.401574
4,283658,The United Empire Loyalists: A Chronicle of th...,missing,missing,6112,598.424000

In [ ]:
col = trainData['PRODUCT_TYPE_ID'].values

#convert the integer values to float
col_float = col.astype(np.float32)


#convert the Numpy array back to a DataFrame column
trainData['PRODUCT_TYPE_ID'] = pd.Series(col_float, index=trainData.index)

col = trainData['PRODUCT_LENGTH'].values

#convert the integer values to float
col_float =col.astype(np.float32)


#convert the Numpy array back to a DataFrame column
trainData['PRODUCT_LENGTH']=pd.Series(col_float, index=trainData.index)

trainData.head()

,PRODUCT_ID,TITLE,BULLET_POINTS,DESCRIPTION,PRODUCT_TYPE_ID,PRODUCT_LENGTH
0,1925202,ArtzFolio Tulip Flowers Blackout Curtain for D...,[LUXURIOUS & APPEALING: Beautiful custom-made ...,missing,1650.0,2125.979980
1,2673191,Marks & Spencer Girls' Pyjama Sets T86_2561C_N...,"[Harry Potter Hedwig Pyjamas (6-16 Yrs),100% c...",missing,2755.0,393.700012
2,2765088,PRIKNIK Horn Red Electric Air Horn Compressor ...,"[Loud Dual Tone Trumpet Horn, Compatible With ...","Specifications: Color: Red, Material: Aluminiu...",7537.0,748.031494
3,1594019,ALISHAH Women's Cotton Ankle Length Leggings C...,[Made By 95%cotton and 5% Lycra which gives yo...,AISHAH Women's Lycra Cotton Ankel Leggings. Br...,2996.0,787.401550
4,283658,The United Empire Loyalists: A Chronicle of th...,missing,missing,6112.0,598.424011

In [ ]:
x_train, x_val, y_train, y_val = train_test_split(trainData.iloc[:,1:5],trainData.iloc[:,5],test_size=0.2, random_state=42)

x_train.info()
y_train.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1799758 entries, 473501 to 2219110
Data columns (total 4 columns):
 #   Column           Dtype
---  ------           -----
 0   TITLE            object
 1   BULLET_POINTS    object
 2   DESCRIPTION      object
 3   PRODUCT_TYPE_ID  float32
dtypes: float32(1), object(3)
memory usage: 61.8+ MB
<class 'pandas.core.series.Series'>
Int64Index: 1799758 entries, 473501 to 2219110
Series name: PRODUCT_LENGTH
Non-Null Count    Dtype
--------------    -----
1799758 non-null  float32
dtypes: float32(1)
memory usage: 20.6 MB

In [ ]:
 x_train , x_val, y_train, y_val = train_test_split(trainData.drop(['PRODUCT_LENGTH','PRODUCT_ID'], axis=1),
                                               trainData['PRODUCT_LENGTH'],
                                               test_size=0.2,
                                                 random_state=42)

In [ ]:
x_train.head()

,TITLE,BULLET_POINTS,DESCRIPTION,PRODUCT_TYPE_ID
473501,Sewell Direct SW-29978 RG59 Pure Copper Conduc...,"[Plenum (CMP) rated,95% Braid, double shield,P...",Siamese cables give you the power to centraliz...,1789.0
1048636,"Looife Colorful Abstract Canvas Wall Art, 24x1...",[☮【WALL DECOR】24x18x1.5(WxHxD) inch solid wood...,<p><i>Contemporary style giclee artwork prints...,6548.0
609127,ArtzFolio Abstract Style Bulletin Board Notice...,[MULTI-PURPOSE USE: Flexible mounting | Use it...,missing,5359.0
784216,HONEYCAT Crystal Bezels Droplet Necklace in Go...,[DESIGN DETAILS: A whisper thin chain necklace...,A whisper thin chain necklace detailed with se...,3365.0
1996772,Fox Men's Furnace Short Sleeve Premium T-Shirt...,[Side seam construction maintains the integrit...,missing,2879.0

In [ ]:
y_train.info()

<class 'pandas.core.series.Series'>
Int64Index: 1799758 entries, 473501 to 2219110
Series name: PRODUCT_LENGTH
Non-Null Count    Dtype
--------------    -----
1799758 non-null  float32
dtypes: float32(1)
memory usage: 20.6 MB

In [ ]:
testData=pd.read_csv("/content/drive/MyDrive/DATA/datasetb2d9982/dataset/test.csv",index_col=False)

In [ ]:
testData.head()

,PRODUCT_ID,TITLE,BULLET_POINTS,DESCRIPTION,PRODUCT_TYPE_ID
0,604373,Manuel d'Héliogravure Et de Photogravure En Re...,NaN,NaN,6142
1,1729783,DCGARING Microfiber Throw Blanket Warm Fuzzy P...,[QUALITY GUARANTEED: Luxury cozy plush polyest...,<b>DCGARING Throw Blanket</b><br><br> <b>Size ...,1622
2,1871949,I-Match Auto Parts Front License Plate Bracket...,"[Front License Plate Bracket Made Of Plastic,D...",Replacement for The Following Vehicles:2020 LE...,7540
3,1107571,PinMart Gold Plated Excellence in Service 1 Ye...,[Available as a single item or bulk packed. Se...,Our Excellence in Service Lapel Pins feature a...,12442
4,624253,"Visual Mathematics, Illustrated by the TI-92 a...",NaN,NaN,6318

In [ ]:
trainData = pd.read_csv("/content/drive/MyDrive/DATA/datasetb2d9982/dataset/train.csv",index_col=False)
trainData =trainData.dropna()
trainData.head()

,PRODUCT_ID,TITLE,BULLET_POINTS,DESCRIPTION,PRODUCT_TYPE_ID,PRODUCT_LENGTH
2,2765088,PRIKNIK Horn Red Electric Air Horn Compressor ...,"[Loud Dual Tone Trumpet Horn, Compatible With ...","Specifications: Color: Red, Material: Aluminiu...",7537,748.031495
3,1594019,ALISHAH Women's Cotton Ankle Length Leggings C...,[Made By 95%cotton and 5% Lycra which gives yo...,AISHAH Women's Lycra Cotton Ankel Leggings. Br...,2996,787.401574
5,2152929,HINS Metal Bucket Shape Plant Pot for Indoor &...,"[Simple and elegant, great for displaying indo...",HINS Brings you the most Elegant Looking Pot w...,5725,950.000000
7,2026580,Delavala Self Adhesive Kitchen Backsplash Wall...,[HIGH QUALITY PVC MATERIAL: The kitchen alumin...,<p><strong>Aluminum Foil Stickers-good kitchen...,6030,984.251967
9,2998633,Hexwell Essential oil for Home Fragrance Oil A...,[100% Pure And Natural Essential Oil Or Fragra...,"Transform your home, workplace or hotel room i...",8201,393.700787

In [ ]:
punctuation_signs = list("?:!.,;")
nltk.download('punkt')
nltk.download('wordnet')
wordnet_lemmatizer = WordNetLemmatizer()
nltk.download('stopwords')
stop_words = list(stopwords.words('english'))

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

In [ ]:
trainData['Title'] = trainData['TITLE'].str.replace("\r", " ")
trainData['Title'] = trainData['Title'].str.replace("\n", " ")
trainData['Title'] = trainData['Title'].str.replace("    ", " ")
trainData['Title'] = trainData['Title'].str.replace('"', '')
trainData['Title'] = trainData['Title'].str.lower()
for punct_sign in punctuation_signs:
  trainData['Title'] = trainData['Title'].str.replace(punct_sign, '')
trainData['Title'] = trainData['Title'].str.replace("'s", "")

<ipython-input-31-27ea8c6fff9b>:7: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  trainData['Title'] = trainData['Title'].str.replace(punct_sign, '')

In [ ]:
final_cols = ["Title", "PRODUCT_LENGTH"]
trainData = trainData[final_cols]
trainData = trainData.iloc[:734736, :]

In [ ]:
testData['Title'] = testData['Title'].str.replace("\r", " ")
testData['Title'] = testData['Title'].str.replace("\n", " ")
testData['Title'] = testData['Title'].str.replace("    ", " ")
testData['Title'] = testData['Title'].str.replace('"', '')
testData['Title'] = testData['Title'].str.lower()
for punct_sign in punctuation_signs:
  testData['Title'] = testData['Title'].str.replace(punct_sign, '')
testData['Title'] = testData['Title'].str.replace("'s", "")

<ipython-input-51-571fdd15e6fe>:7: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  testData['Title'] = testData['Title'].str.replace(punct_sign, '')

In [ ]:
final_cols = ["Title", "PRODUCT_ID"]
testData = testData[final_cols]

In [ ]:
trainData.head()

                                               Title  PRODUCT_LENGTH
2  priknik horn red electric air horn compressor ...      748.031495
3  alishah women cotton ankle length leggings com...      787.401574
5  hins metal bucket shape plant pot for indoor &...      950.000000
7  delavala self adhesive kitchen backsplash wall...      984.251967
9  hexwell essential oil for home fragrance oil a...      393.700787

In [ ]:
testData.head()

                                               Title  PRODUCT_ID
0  manuel d'héliogravure et de photogravure en re...      604373
1  dcgaring microfiber throw blanket warm fuzzy p...     1729783
2  i-match auto parts front license plate bracket...     1871949
3  pinmart gold plated excellence in service 1 ye...     1107571
4  visual mathematics illustrated by the ti-92 an...      624253

In [ ]:
trainData.isna().sum()

Title             0
PRODUCT_LENGTH    0
dtype: int64

In [ ]:
testData["Title"].fillna("No Data", inplace=True)

In [ ]:
testData.isna().sum()

Title         0
PRODUCT_ID    0
dtype: int64

In [ ]:
X_train, X_test, y_train = trainData["Title"], testData["Title"], trainData["PRODUCT_LENGTH"]

In [ ]:
tfidf = TfidfVectorizer(stop_words='english', ngram_range=(1,2), min_df=5)
print('1')
X_train_vectors_tfidf = tfidf.fit_transform(X_train)
print(X_train_vectors_tfidf.shape)
print('1')
X_test_vectors_tfidf = tfidf.transform(X_test)
print(X_test_vectors_tfidf.shape)

1
(35000, 19349)
1
(734736, 19349)

In [ ]:
d={"PRODUCT_LENGTH":X_test_vectors_tfidf}

In [ ]:
d

{'PRODUCT_LENGTH': <734736x19349 sparse matrix of type '<class 'numpy.float64'>'
 	with 7640775 stored elements in Compressed Sparse Row format>}

In [ ]:
sampleData=pd.read_csv("/content/drive/MyDrive/DATA/datasetb2d9982/dataset/sample_submission.csv", index_col=False)

In [ ]:
sampleData

        PRODUCT_ID  PRODUCT_LENGTH
0           604373      701.093794
1          1729783      734.506163
2          1871949      741.360258
3          1107571      730.327767
4           624253      666.847946
...            ...             ...
734731      921419      733.838809
734732     2456362      746.810825
734733      841529      691.127128
734734     1190194      757.643591
734735     1040810      754.110288

[734736 rows x 2 columns]